export const UPLOAD_FILE_BEGIN = "UPLOAD_FILE_BEGIN";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR";
export const VALIDATION_ERROR = "VALIDATION_ERROR";
export const SET_INITIAL_STATE = "SET_INITIAL_STATE";
