export const UPLOAD_FILE_BEGIN = "UPLOAD_FILE_BEGIN";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR";
export const RESET_CDR_STATES = "RESET_CDR_STATES";
export const GET_CDR_BEGIN = "GET_CDR_BEGIN";
export const GET_CDR_SUCCESS = "GET_CDR_SUCCESS";
export const GET_CDR_ERROR = "GET_CDR_ERRORS";
